---
# tasks file for updating dotfiles configuration
- name: Downloading your {{ fucking }} dotfiles
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dir }}"

# Configure tmux
- name: "Configuring {{ item }}"
  copy: 
    src: "{{ dotfiles_dir }}/{{ item }}"
    dest: "~/"
  loop:
    - ".tmux.conf"
    - ".zshrc"
    - ".profile"
    - ".p10k.zsh"
