---
- name: Create direnv folder
  block:
    - name: Check if folder exists
      stat:
        path: "{{ direnv_dir }}"
      register: stat_result

    - name: Create the file, if it doesnt exist already
      file:
        path: "{{ direnv_dir }}"
        force: yes
        state: directory

- name: Install direnv
  get_url:
    url: "{{ direnv_url }}"
    dest: "{{ direnv_dir }}"
