---
- name: "Is {{ pkg }} in our packages?"
  package_facts:
    manager: auto

- name: "Installing {{ pkg }} into your {{ butthole }}"
  package:
    name: "{{ pkg }}"
    state: latest
    install_recommends: yes
  when: 'pkg not in ansible_facts.packages'

