---
# tasks file for neovim
- name: Adding go aliases to zshrc
  block:
  - name: Add go to path
    lineinfile:
      path: "{{ zshrc_dir }}"
      line: "{{ item }}"
      loop:
        - export PATH=$PATH:~/go/bin/
        - export GOROOT=/usr/local/go-1.18
        - export GOPATH=$HOME/go
        - export GOBIN=$GOPATH/local_bin
        - export PATH=$PATH:$GOROOT/bin
        - export GO111MODULE="on"

  - name: Add Go direnv handler
    lineinfile:
      path: "{{ zshrc_dir }}"
      line: "{{ item }}"                         
      loop:
        - " # Start projects GO env with Direnv"
        - setgoenv() { echo "export GOPATH=$(pwd)" >> .envrc | direnv allow . }
