---
# Install pandoc if not already installed.
- name: Check if pandoc is installed 
  block:
    - name: Getting facts
      package_facts:
        manager: auto

    - name: Is pandoc in our packages?
      set_fact: 
        installed: "{{ ansible_facts.packages['pandoc'] }}" 
      when: "'pandoc' in ansible_facts.packages"

- name: Ensure download location exists
  file:
    path: "{{ downloads_dir }}"
    state: directory
  when: installed == 0

- name: Download pandoc
  get_url:
    url: "{{ pandoc_url }}"
    dest: "{{ downloads_dir }}"
  when: installed == 0

- name: Install pandoc
  shell: "tar xvzf {{ downloads_dir }}/{{ pandoc_file_tar }} --strip-components 1 -C {{ user_bin_dir }}"
  when: installed == 0
  
