---
# tasks file for mongodb
# TODO: Disabled for now, until I find a replacement for openGR keys on apt-key
#- name: Install mongodb
#  block:
#    - name: Download little mongo
#      get_url:
#        url: "{{ mongo_server_url }}"
#        dest: "{{ downloads_dir }}"

#    - name: Install mongish
#      shell: apt-key add -

#- name: Check if little mongish is alright
#  package_facts:
#    manager: "auto"

#- name: Try to install mongodb again but using 'gnupg'
#  block:
#    - name: Installing gnup
#      package: 
#        name: gnupg
#        state: latest
  
#    - name: Install mongish once more
#      shell: apt-key add -

#  when: mongodb not in ansible_facts.packages
