---
- name: Install findutils
  package:
    name: findutils
    state: latest

- name: Install fd-find
  package:
    name: fd-find
    state: latest 

- name: Create link to fd-find 
  shell: ln -s $(which fdfind) "{{ local_bin }}"/fd

