---
# tasks for pkgs
- name: "Installing your primary {{ asshole }} pkgs"
  include_tasks: "install.yml"
  vars:
    pkg: "{{ item }}"
  loop:
    - "git"
    - "unzip"
    - "gzip"
    - "golang"
    - "curl"
    - "wget"
    - "software-properties-common"
