---
# tasks for pkgs
- name: Installing your {{ asshole }} pkgs
  include_tasks: "{{ item }}"
  loop:
    - git.yml
    - direnv.yml
    - fd-find.yml
    - gzip.yml
    - pipenv.yml
    - progress.yml
