---
- name: "Is {{ pkg }} in our packages?"
  package_facts:
    manager: auto

- name: "Install {{ pkg }} in your {{ ass }}"
  package:
    name: "{{ pkg }}"
    state: latest
    install_recommends: yes
  when: "{{ pkg }} in ansible_facts.packages"

