---
# Run docker role
- name: Starting Docker's and Docker-Compose's tasks
  hosts: all
  become: true
  vars_files:
    - vars/docker-vars.yml
    - vars/variables.yml
    # TODO: Enable to install docker
#
#   tasks:
#     - name: Install required system packages for Docker
#       package:
#         name: "{{ docker_required_packages }}"
#         state: latest
#         update_cache: no
#
#     - name: Add Docker GPG key
#       apt_key:
#         url: "{{ docker_gpg_url }}"
#         state: present
#
#     - name: Add Docker repository
#       apt_repository:
#         update_cache: no
#         repo: "{{ docker_repo }}"
#         state: present
#
#     - name: Install Docker
#       package:
#         name: "{{ docker_packges }}"
#         state: latest
#
#     - name: Install Python Docker module
#       pip:
#         name: docker
#
#     - name: Add adminstrator to docker group
#       user:
#         name: "{{ admin_user }}"
#         groups: docker
#         append: yes
#
#     - name: Install Docker Compose
#       get_url:
#         url: "{{ docker_compose_url }}"
#         dest: /usr/local/bin/docker-compose
#         mode: u+x,g+x,o+x
#
#     - name: Check installation of Docker Compose
#       shell: docker-compose --version
