---
# Run Neovim role
- name: Starting Neovim's tasks
  hosts: all
  become: true
  vars_files: 
    - vars/variables.yml
    - vars/neovim-vars.yml

  tasks: 
    - name: Installing Neo-Fucking-Vim
      get_url:
        url: "{{ neovim_url }}"
        dest: "{{ downloads_dir }}"
  
    - name: Unzip it baby  
      unarchive:
        src: "{{ downloads_dir }}/{{ neovim_tar }}"
        dest: "{{ software_dir }}"
        creates: "{{ neovim_install_dir }}"
  
    # Download and set neovim configuration
    - name: Downloading your one in a kind configuration 
      git:
        repo: "{{ neovim_repo }}"
        dest: "{{ neovim_config_dir }}"
    
