---
# Install all packages
- name: Starting packages's tasks
  hosts: all
  become: true
  vars_files: 
    - vars/variables.yml
    - vars/pkgs-vars.yml
    - vars/golang-vars.yml
    - vars/direnv-vars.yml

  # Install all PPAs
  tasks:  
    - name: "Installing {{ pkgs }} into your butthole"
      package:
        name: "{{ pkgs }}"
        state: latest
        install_recommends: yes
  
    # Install golang
    - name: "Installing golang"
      unarchive:
        src: "{{ golang_url }}"
        dest: "{{ usr_local_bin_dir }}"
        remote_src: yes
    
    # Install yarn
    - name: Installing yarn
      shell: "npm install -g yarn"
    
    # Install direnv
    - name: Check if direnv folder exists
      stat:
        path: "{{ direnv_dir }}"
      register: stat_result

    - name: Create the file, if it doesnt exist already
      file:
        path: "{{ direnv_dir }}"
        state: directory
      when: stat_result == None

    - name: Install direnv
      get_url:
        url: "{{ direnv_url }}"
        dest: "{{ direnv_dir }}"

    # Install exa
    - name: Downloading exa
      shell: "curl -Lo exa.zip {{ exa_url }}"

    - name: Installing exa
      shell: "unzip -q exa.zip bin/exa -d {{ usr_local }}"


