---
# Install all packages
- name: Starting packages's tasks
  hosts: all
  become: true
  vars_files: 
    - vars/variables.yml
    - vars/pkgs-vars.yml

  # Install all PPAs
  block:  
  - name: "Is {{ pkgs }} in our packages?"
    package_facts:
      manager: auto
  
  - name: "Installing {{ pkgs }} into your {{ butthole }}"
    package:
      name: "{{ pkgs }}"
      state: latest
      install_recommends: yes
    when: 'pkgs not in ansible_facts.packages'
  
# Install golang
- name: "Installing golang"
  unarchive:
    src: "{{ golang_url }}"
    dest: /usr/local/bin
    remote_src: yes

# Install yarn
- name: Installing yarn
  shell: "npm install -g yarn"

# Install direnv
- name: Create direnv folder
  block:
    - name: Check if folder exists
      stat:
        path: "{{ direnv_dir }}"
      register: stat_result

    - name: Create the file, if it doesnt exist already
      file:
        path: "{{ direnv_dir }}"
        state: directory
      when: stat_result == None

- name: Install direnv
  vars_files:
    - vars/direnv-vars.yml
  get_url:
    url: "{{ direnv_url }}"
    dest: "{{ direnv_dir }}"
