---
# Set up the system 
# Needs to run first than other playbooks
- name: System setup
  hosts: all
  become: true
  vars_files: 
    - vars/variables.yml

  pre_tasks:
    - name: Create software folder
      file:
        path: "{{ software_dir }}"
        state: directory

    - name: Create downloads folder
      file:
        path: "{{ downloads_dir }}"
        state: directory

    - name: "Updating your {{ asshole }}"
      shell: |
        apt-get update
        apt-get -y upgrade
