---
# Set up the system 
# Needs to run first than other playbooks
- name: System setup
  hosts: all
  become: true
  vars_files: 
    - vars/variables.yml

  pre_tasks:
    - name: Create software folder
      file:
        path: "{{ software_dir }}"
        state: directory

    - name: Create downloads folder
      file:
        path: "{{ downloads_dir }}"
        state: directory

    - name: Create config folder
      file:
        path: "{{ config_dir }}"
        state: directory

    - name: Create fish folder
      file:
        path: "{{ fish_config_dir }}"
        state: directory

    - name: Create omf folder
      file:
        path: "{{ omf_config_dir }}"
        state: directory

    - name: Create lazygit folder
      file:
        path: "{{ lazygit_dir }}"
        state: directory

    - name: Create neovim folder
      file:
        path: "{{ neovim_config_dir }}"
        state: directory

    - name: "Updating your butthole..."
      shell: |
        apt update
        apt -y upgrade
