---
- name: Install zsh for Linux.
  package:
    name: zsh
    state: present

- name: Get zsh installed path.
  command: "which zsh"
  register: zsh_installed_path
  changed_when: false

- name: Set user shell to zsh.
  user:
    name: "{{ admin_user }}"
    shell: "{{ zsh_installed_path.stdout }}"

# tasks for Oh My Zsh
- name: Installing oh-my-zsh
  shell: "sh -c \"$(curl -fsSL {{ ohmyzsh_installer }})\""
    
